### ISSUE TITLE
Multiple file types

### ISSUE THREAD

**Issue by igorrafael** [UnityCommunity/UnityLibrary#5]
I would like to submit this interesting [CommandBuffer+Stencil example](https://forum.unity3d.com/threads/has-anyone-ever-gotten-a-stencil-buffer-to-copy-with-commandbuffer-blit.432503/) but the current folder structure does not have a place for multiple file types.

I was thinking about creating a "Projects" folder and add a whole unity project to it (with the contents of the [unitypackage](https://forum.unity3d.com/attachments/commandbufferusepreviousrendertexture-unitypackage.202936/) from the example).

Does anyone suggest a different approach?

**Comment by unitycoder** [comment]
Yeah, been thinking about this also..(had those couple scripts that require more than 1 script..)
Go ahead with those folders, can arrange more later if get better ideas..

Still can add some subfolder like,
Projects/Rendering/ (since its related to UnityEngine.Rendering)

**Comment by EmpireWorld** [comment]
@igorrafael Hi.

You can submit your complete projects as external repositories to [Unity Community](https://github.com/UnityCommunity/) and then add a link to them via [Unity Library](https://github.com/UnityCommunity/UnityLibrary/).

Because [Unity Library](https://github.com/UnityCommunity/UnityLibrary/) is a place for small utilities for Unity not a container for complete projects.

Thanks.

**Comment by unitycoder** [comment]
yeah, that's good idea (and its enabled that members can create new repositories)

**Comment by EmpireWorld** [comment]
@igorrafael Because we can publish our completed projects as separated repositories to [Unity Community](https://github.com/UnityCommunity) i close this issue.

But still you can publish your completed projects useful things like scripts, shaders, ... to [UnityLibrary](https://github.com/UnityCommunity/UnityLibrary).

Thanks.
